---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: rke2-control-plane-system/rke2-control-plane-serving-cert
  labels:
    cluster.x-k8s.io/provider: control-plane-rke2
  name: rke2-control-plane-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: rke2-control-plane-webhook-service
      namespace: rke2-control-plane-system
      path: /validate-controlplane-cluster-x-k8s-io-v1alpha1-rke2controlplane
  failurePolicy: Fail
  name: vrke2controlplane.kb.io
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rke2controlplanes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: rke2-control-plane-webhook-service
      namespace: rke2-control-plane-system
      path: /validate-controlplane-cluster-x-k8s-io-v1alpha1-rke2controlplanetemplate
  failurePolicy: Fail
  name: vrke2controlplanetemplate.kb.io
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rke2controlplanetemplates
  sideEffects: None
